#!/usr/bin/env bash

# common

docker build -t kamilsk/golang:1.5-alpine \
             -f 1.5-alpine.Dockerfile \
             .
docker push kamilsk/golang:1.5-alpine

docker build -t kamilsk/golang:1.6-alpine \
             -f 1.6-alpine.Dockerfile \
             .
docker push kamilsk/golang:1.6-alpine

docker build -t kamilsk/golang:1.7-alpine \
             -t kamilsk/golang:alpine \
             -f 1.7-alpine.Dockerfile \
             .
docker push kamilsk/golang:1.7-alpine
docker push kamilsk/golang:alpine

# tooling

docker build -t kamilsk/go-tools:alpine \
             -f tools.Dockerfile \
             .
docker push kamilsk/go-tools:alpine
