[[constraint]]
  name = "github.com/gofrs/uuid"
  branch = "master"

[[constraint]]
  name = "github.com/google/uuid"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-uuid"
  branch = "master"

[[constraint]]
  name = "github.com/jakehl/goid"
  branch = "master"

[[constraint]]
  name = "github.com/kevinburke/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/oklog/ulid"
  branch = "master"

[[constraint]]
  name = "github.com/pborman/uuid"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  branch = "master"

[[constraint]]
  name = "gopkg.in/myesui/uuid.v1"
  version = "v1"

[prune]
  go-tests = true
  unused-packages = true
