version: "3"

services:
  nginx:
    image: nginx:mainline-alpine

  proxy:
    image: kamilsk/nginx:alpine
    build:
      context:    .
      dockerfile: mainline-alpine.Dockerfile
    command: ["kamil.samigullin.info:samigullin.info,www.samigullin.info", "www.octolab.org:octolab.org"]
    depends_on:
    - nginx
    environment:
    - LE_ENABLED=true
    - LE_EMAIL=kamil@samigullin.info
    - DEV_ENABLED=true
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./etc/conf.d:/etc/nginx/sites-available
    - ./etc/ssl:/etc/nginx/ssl
