[[constraint]]
  name = "github.com/juju/errors"
  branch = "master"

[[constraint]]
  name = "github.com/oxequa/grace"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
