list:

- name: github.com/jmoiron/sqlx
  src:  https://github.com/jmoiron/sqlx
  tags: []
  used:   false
  viewed: false

- name: github.com/jinzhu/gorm
  src:  https://github.com/jinzhu/gorm
  tags: []
  used:   false
  viewed: false

- name: github.com/samonzeweb/godb
  src:  https://github.com/samonzeweb/godb
  tags: []
  used:   false
  viewed: false

- name: github.com/github/gh-ost
  src:  https://github.com/github/gh-ost
  tags: []
  used:   false
  viewed: false
