list:

- name: github.com/apex/log
  src:  https://github.com/apex/log
  tags: []
  used:   false
  viewed: false

- name: github.com/golang/glog
  src:  https://github.com/golang/glog
  tags: []
  used:   false
  viewed: false

- name: github.com/inconshreveable/log15
  src:  https://github.com/inconshreveable/log15
  tags: []
  used:   false
  viewed: false

- name: github.com/uber-go/zap
  src:  https://github.com/uber-go/zap
  tags: []
  used:   false
  viewed: false

- name: github.com/sirupsen/logrus
  src:  https://github.com/sirupsen/logrus
  tags: []
  used:   false
  viewed: false

- name: github.com/happierall/l
  src:  https://github.com/happierall/l
  tags: []
  used:   false
  viewed: false
