packages:
- package: hirak/prestissimo
  src: https://github.com/hirak/prestissimo
- package: sensiolabs/melody
  src: https://github.com/sensiolabs/melody
- package: davidrjonas/composer-lock-diff
  src: https://github.com/davidrjonas/composer-lock-diff
